version: "3"
services: 
  jenkins:
    container_name: dev-jenkins
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - "./db/jenkins-data/:/var/jenkins_home"

  nexus:
    container_name: dev-nexus
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    environment:
      - "INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
      - "NEXUS_CONTEXT=nexus"
    volumes:
      - "./db/nexus-data:/nexus-data"

  sonarqube: 
    container_name: dev-sonarqube
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    volumes:
      - "./db/sonar-data/data:/opt/sonarqube/data"
      - "./db/sonar-data/extensions:/opt/sonarqube/extensions"
      - "./db/sonar-data/logs:/opt/sonarqube/logs"

