version: "3"
services: 
  jenkins:
    container_name: my-heroku-jenkins
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - "./jenkins-data/:/var/jenkins_home"
